# Use the official Python image as the base
FROM python:3.10

# Additonal tools
RUN apt-get update
RUN apt-get install -y iputils-ping
RUN apt-get install -y inetutils-traceroute
RUN apt-get install -y iproute2
RUN apt-get install -y curl telnet dnsutils vim



# Set the working directory inside the container
WORKDIR /app

# Copy your FastAPI app files into the container
COPY . .
 
# Install dependencies (if any)
RUN pip install -r requirements.txt

# Expose the port your FastAPI app will run on
EXPOSE 8000

# Start the FastAPI app using Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
