# This setup is for the development opertions

name: inventory-setup CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-docker-compose:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file
        run: |
          echo MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} >> .env
          echo MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} >> .env
          echo POSTGRESS_USER=${{ secrets.POSTGRESS_USER }} >> .env
          echo POSTGRESS_PASSWORD=${{ secrets.POSTGRESS_PASSWORD }} >> .env

      - name: Run Docker Compose
        run: |
          docker compose -f mongo_services.yml --env-file .env up -d
